-----------------삭제------------------
--접속유저의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--접속유저의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/
---------------------------------------
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "CLASS" CASCADE CONSTRAINTS;
DROP TABLE "LESSON" CASCADE CONSTRAINTS;
DROP TABLE "INQUIRY" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "MEM_PAY" CASCADE CONSTRAINTS;
DROP TABLE "QNA" CASCADE CONSTRAINTS;
DROP TABLE "VIDEO" CASCADE CONSTRAINTS;
DROP TABLE "CLASS_FAQ" CASCADE CONSTRAINTS;
DROP TABLE "TUTOR" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "SALARY" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "REPLY" CASCADE CONSTRAINTS;
DROP TABLE "MEM_VIDEO" CASCADE CONSTRAINTS;
DROP TABLE "CURRICULUM" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;

CREATE TABLE "MEMBER" (
	"MEM_NO"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(100)		NOT NULL,
	"MEM_PWD"	VARCHAR2(100)		NOT NULL,
	"MEM_NAME"	VARCHAR2(50)		NOT NULL,
	"NICKNAME"	VARCHAR2(50)		NOT NULL,
	"BIRTHDAY"	VARCHAR2(50)		NOT NULL,
	"GENDER"	VARCHAR2(1)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NOT NULL,
	"PHONE"	VARCHAR2(50)		NOT NULL,
	"MEM_PIC"	VARCHAR2(1000)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"REPORT_COUNT"	NUMBER		NULL,
	"OUT_DATE"	DATE		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	CONSTRAINT "PK_MEMBER" PRIMARY KEY("MEM_NO")
);

COMMENT ON COLUMN "MEMBER"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PWD" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_NAME" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."BIRTHDAY" IS '회원 생년월일';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEM_PIC" IS '회원 사진';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MODIFY_DATE" IS '회원 수정일';

COMMENT ON COLUMN "MEMBER"."REPORT_COUNT" IS '회원 신고 누적수';

COMMENT ON COLUMN "MEMBER"."OUT_DATE" IS '회원 탈퇴일';

COMMENT ON COLUMN "MEMBER"."STATUS" IS '회원 상태';

CREATE SEQUENCE SEQ_MNO NOCACHE;

CREATE TABLE "LESSON" (
	"LESSON_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"LESSON_FORM"	VARCHAR2(20)		NOT NULL,
	"LESSON_TYPE"	VARCHAR2(20)		NOT NULL,
	"LESSON_GROUP"	NUMBER		NOT NULL,
	"LESSON_CATEGORY"	VARCHAR2(20)		NOT NULL,
	"LESSON_TITLE"	VARCHAR2(200)		NOT NULL,
	"LESSON_COVER_IMG"	VARCHAR2(1000)		NOT NULL,
	"LESSON_INSTR"	CLOB		NOT NULL,
	"LESSON_CONT_NO"	NUMBER		NULL,
	"LESSON_PREPARE"	VARCHAR2(500)		NULL,
	"LESSON_TARGET"	VARCHAR2(500)		NOT NULL,
	"LIKE_COUNT"	NUMBER	DEFAULT 0	NULL,
	"LESSON_STATUS"	VARCHAR2(70)	DEFAULT '보류'	NOT NULL,
	"STATUS_HOLD"	NUMBER		NOT NULL,
	"H_REASON"	VARCHAR2(500)		NULL,
	"R_REASON"	VARCHAR2(500)		NULL,
	"PRICE"	VARCHAR2(100)		NOT NULL,
	"TIME"	VARCHAR2(30)		NOT NULL,
	"TOTAL_COUNT"	VARCHAR2(10)		NOT NULL,
	"PERIOD"	VARCHAR2(10)		NOT NULL,
	"DISC_STATUS"	VARCHAR2(70)	DEFAULT '미적용'	NOT NULL,
	"DISCOUNT_PERIOD"	VARCHAR2(10)		NULL,
	"DISCOUNT"	VARCHAR2(10)		NULL,
	"PAY_TOTAL"	VARCHAR2(100)		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	CONSTRAINT "PK_LESSON" PRIMARY KEY("LESSON_NO")
);

COMMENT ON COLUMN "LESSON"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "LESSON"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "LESSON"."LESSON_FORM" IS '수업형태';

COMMENT ON COLUMN "LESSON"."LESSON_TYPE" IS '수업유형';

COMMENT ON COLUMN "LESSON"."LESSON_GROUP" IS '수업참여인원';

COMMENT ON COLUMN "LESSON"."LESSON_CATEGORY" IS '수업카테고리';

COMMENT ON COLUMN "LESSON"."LESSON_TITLE" IS '클래스제목';

COMMENT ON COLUMN "LESSON"."LESSON_COVER_IMG" IS '커버이미지';

COMMENT ON COLUMN "LESSON"."LESSON_INSTR" IS '클래스 설명';

COMMENT ON COLUMN "LESSON"."LESSON_CONT_NO" IS '컨텐츠갯수';

COMMENT ON COLUMN "LESSON"."LESSON_PREPARE" IS '준비물';

COMMENT ON COLUMN "LESSON"."LESSON_TARGET" IS '클래스대상';

COMMENT ON COLUMN "LESSON"."LIKE_COUNT" IS '좋아요 카운트';

COMMENT ON COLUMN "LESSON"."LESSON_STATUS" IS '클래스승인여부(보류/승인/거절)';

COMMENT ON COLUMN "LESSON"."STATUS_HOLD" IS '삭제보류기간';

COMMENT ON COLUMN "LESSON"."H_REASON" IS '클래스보류사유';

COMMENT ON COLUMN "LESSON"."R_REASON" IS '클래스거절사유';

COMMENT ON COLUMN "LESSON"."PRICE" IS '클래스 시간당 가격';

COMMENT ON COLUMN "LESSON"."TIME" IS '1 회당 수업 시간';

COMMENT ON COLUMN "LESSON"."TOTAL_COUNT" IS '클래스 총  수업 횟수';

COMMENT ON COLUMN "LESSON"."PERIOD" IS '클래스 진행기간(주단위)';

COMMENT ON COLUMN "LESSON"."DISC_STATUS" IS '클래스 할인 적용여부(적용/미적용)';

COMMENT ON COLUMN "LESSON"."DISCOUNT_PERIOD" IS '클래스 할인기간';

COMMENT ON COLUMN "LESSON"."DISCOUNT" IS '클래스 할인율';

COMMENT ON COLUMN "LESSON"."PAY_TOTAL" IS '클래스 총금액(수수료 적용X)';

COMMENT ON COLUMN "LESSON"."STATUS" IS '클래스상태(Y/N)';

CREATE SEQUENCE SEQ_LESNO NOCACHE; 	-- CLASS

CREATE TABLE "INQUIRY" (
	"INQ_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"INQ_TITLE"	VARCHAR2(200)		NOT NULL,
	"INQ_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"INQ_TYPE"	VARCHAR2(20)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANSWER_DATE"	DATE		NULL,
	"ANSWER_CONTENT"	VARCHAR2(4000)		NULL,
	"INQ_FILE"	VARCHAR2(1000)		NULL,
	"ORIGIN_FILE"	CLOB		NULL,
	"TYPE_STATUS"	VARCHAR2(15)		NOT NULL,
	"STATUS"	VARCHAR2(2)	DEFAULT 'N'	NOT NULL,
	"RE_STATUS"	VARCHAR2(12)	DEFAULT '접수'	NOT NULL,
	CONSTRAINT "PK_INQUIRY" PRIMARY KEY("INQ_NO")
);

COMMENT ON COLUMN "INQUIRY"."INQ_NO" IS '1:1문의 번호';

COMMENT ON COLUMN "INQUIRY"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "INQUIRY"."INQ_TITLE" IS '1:1문의 제목';

COMMENT ON COLUMN "INQUIRY"."INQ_CONTENT" IS '1:1문의 내용';

COMMENT ON COLUMN "INQUIRY"."INQ_TYPE" IS '1:1문의 유형 ( 사용자 / 튜터 / 기타 / 클래스 )';

COMMENT ON COLUMN "INQUIRY"."ENROLL_DATE" IS '1:1문의 날짜';

COMMENT ON COLUMN "INQUIRY"."ANSWER_DATE" IS '1:1답변 날짜';

COMMENT ON COLUMN "INQUIRY"."ANSWER_CONTENT" IS '1:1답변 내용';

COMMENT ON COLUMN "INQUIRY"."INQ_FILE" IS '1:1문의 첨부파일';

COMMENT ON COLUMN "INQUIRY"."ORIGIN_FILE" IS '1:1 문의 원본파일';

COMMENT ON COLUMN "INQUIRY"."TYPE_STATUS" IS '공개여부(공개/비공개)';

COMMENT ON COLUMN "INQUIRY"."STATUS" IS '삭제여부( Y / N )';

COMMENT ON COLUMN "INQUIRY"."RE_STATUS" IS '답변여부 ( 접수 / 완료 )';

CREATE SEQUENCE SEQ_INQNO NOCACHE; 	--INQUIRY

CREATE TABLE "LIKE" (
	"LESSON_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	CONSTRAINT "PK_LIKE" PRIMARY KEY("LESSON_NO","MEM_NO")
);

COMMENT ON COLUMN "LIKE"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "LIKE"."MEM_NO" IS '회원 번호';

CREATE TABLE "MEM_PAY" (
	"MEM_PAY_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	"TYPE"	VARCHAR2(50)		NOT NULL,
	"REPAYMENT"	VARCHAR2(100)		NULL,
	"PAYMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CANCEL_DATE"	DATE		NULL,
	"STATUS"	VARCHAR2(30)	DEFAULT '결제 대기'	NOT NULL,
	"DEL_NAME"	VARCHAR2(50)		NULL,
	"DEL_NO"	VARCHAR2(100)		NULL,
	"DEL_STATUS"	VARCHAR2(100)	DEFAULT '배송전'	NOT NULL,
	CONSTRAINT "PK_MEM_PAY" PRIMARY KEY("MEM_PAY_NO")
);

COMMENT ON COLUMN "MEM_PAY"."MEM_PAY_NO" IS '클래스 결제번호';

COMMENT ON COLUMN "MEM_PAY"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "MEM_PAY"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "MEM_PAY"."TYPE" IS '클래스 결제방법(신용카드/무통장)';

COMMENT ON COLUMN "MEM_PAY"."REPAYMENT" IS '클래스 환불계좌';

COMMENT ON COLUMN "MEM_PAY"."PAYMENT_DATE" IS '클래스 결제 날짜';

COMMENT ON COLUMN "MEM_PAY"."CANCEL_DATE" IS '클래스 결제 취소 날짜';

COMMENT ON COLUMN "MEM_PAY"."STATUS" IS '클래스 결제 상태(결제 승인/ 결제 취소/ 결제 대기)';

COMMENT ON COLUMN "MEM_PAY"."DEL_NAME" IS '택배사';

COMMENT ON COLUMN "MEM_PAY"."DEL_NO" IS '운송장 번호';

COMMENT ON COLUMN "MEM_PAY"."DEL_STATUS" IS '배송상태(배송전 / 배송중 / 배송완료)';

CREATE SEQUENCE SEQ_MPAY_NO NOCACHE; 	--MEM_PAY

CREATE TABLE "QNA" (
	"QA_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	"QUESTION"	VARCHAR2(4000)		NOT NULL,
	"ANSWER"	VARCHAR2(4000)		NULL,
	"Q_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"A_ENROLL_DATE"	DATE		NULL,
	"Q_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"A_STATUS"	VARCHAR2(1)		NULL,
	CONSTRAINT "PK_QNA" PRIMARY KEY("QA_NO")
);

COMMENT ON COLUMN "QNA"."QA_NO" IS 'QNA 번호';

COMMENT ON COLUMN "QNA"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "QNA"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "QNA"."QUESTION" IS '질문';

COMMENT ON COLUMN "QNA"."ANSWER" IS '답변';

COMMENT ON COLUMN "QNA"."Q_ENROLL_DATE" IS '질문 작성일';

COMMENT ON COLUMN "QNA"."A_ENROLL_DATE" IS '답변 작성일';

COMMENT ON COLUMN "QNA"."Q_STATUS" IS '질문삭제여부';

COMMENT ON COLUMN "QNA"."A_STATUS" IS '답변삭제여부';

CREATE TABLE "VIDEO" (
	"VIDEO_NO"	NUMBER		NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	"VIDEO_URL"	VARCHAR2(4000)		NOT NULL,
	"VIDEO_CONT"	VARCHAR2(2000)		NOT NULL,
    CONSTRAINT "PK_VIDEO" PRIMARY KEY("VIDEO_NO")
);

COMMENT ON COLUMN "VIDEO"."VIDEO_NO" IS '비디오 번호';

COMMENT ON COLUMN "VIDEO"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "VIDEO"."VIDEO_URL" IS '비디오';

COMMENT ON COLUMN "VIDEO"."VIDEO_CONT" IS '영상소개';

CREATE SEQUENCE SEQ_VNO NOCACHE;	--VIDEO

CREATE TABLE "CLASS_FAQ" (
	"LESSON_NO"	NUMBER		NOT NULL,
	"FAQ_QUESTION"	VARCHAR2(4000)		NOT NULL,
	"FAQ_ANSWER"	VARCHAR2(4000)		NOT NULL
);

COMMENT ON COLUMN "CLASS_FAQ"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "CLASS_FAQ"."FAQ_QUESTION" IS '질문';

COMMENT ON COLUMN "CLASS_FAQ"."FAQ_ANSWER" IS '답변';

CREATE TABLE "TUTOR" (
	"MEM_NO"	NUMBER		NOT NULL,
	"TUTOR_PIC"	VARCHAR2(4000)		NULL,
	"TUTOR_INFO"	VARCHAR2(4000)		NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"STATUS"		VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	CONSTRAINT "PK_TUTOR" PRIMARY KEY("MEM_NO")
);

COMMENT ON COLUMN "TUTOR"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "TUTOR"."TUTOR_PIC" IS '프로필 사진';

COMMENT ON COLUMN "TUTOR"."TUTOR_INFO" IS '튜터 소개';

COMMENT ON COLUMN "TUTOR"."MODIFY_DATE" IS '튜터 수정일';

COMMENT ON COLUMN "TUTOR"."STATUS" IS '튜터 상태';

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TYPE"	VARCHAR2(50)		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(500)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	CONSTRAINT "PK_NOTICE" PRIMARY KEY("NOTICE_NO")
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항 번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_TYPE" IS '공지사항 타입( MEMBER/ TUTOR)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지사항 제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지사항 내용';

COMMENT ON COLUMN "NOTICE"."ENROLL_DATE" IS '공지사항 작성일';

COMMENT ON COLUMN "NOTICE"."MODIFY_DATE" IS '공지사항 수정일';

COMMENT ON COLUMN "NOTICE"."STATUS" IS '공지사항 상태 (일반 공지-Y/ 중요공지-R / 삭제-N)';

CREATE SEQUENCE SEQ_NNO NOCACHE;	--NOTICE

CREATE TABLE "SALARY" (
	"LESSON_NO"	NUMBER		NOT NULL,
	"FEE"	VARCHAR2(500)		NULL,
	"SALARY_TOTAL"	VARCHAR2(1000)		NULL,
	"ACCOUNT"	VARCHAR2(1000)		NOT NULL,
	"STATUS"	VARCHAR2(100)	DEFAULT '미정산'	NOT NULL,
	"SALARY_DATE"	DATE		NULL
);

COMMENT ON COLUMN "SALARY"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "SALARY"."FEE" IS '수수료';

COMMENT ON COLUMN "SALARY"."SALARY_TOTAL" IS '총 월급';

COMMENT ON COLUMN "SALARY"."ACCOUNT" IS '정산받을 계좌';

COMMENT ON COLUMN "SALARY"."STATUS" IS '정산 상태';

COMMENT ON COLUMN "SALARY"."SALARY_DATE" IS '정산일';

CREATE TABLE "REPORT" (
	"MEM_NO"	NUMBER		NOT NULL,
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPORT_TYPE"	VARCHAR2(50)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	VARCHAR2(10)	DEFAULT '미처리'	NOT NULL
);

COMMENT ON COLUMN "REPORT"."MEM_NO" IS '신고자';

COMMENT ON COLUMN "REPORT"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPORT"."REPORT_TYPE" IS '신고사유';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고일';

COMMENT ON COLUMN "REPORT"."STATUS" IS '게시글처리상태(처리/미처리)';

CREATE TABLE "REVIEW" (
	"REVIEW_NO"	NUMBER		NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"STAR"	NUMBER	DEFAULT 0	NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(3000)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	CONSTRAINT "PK_REVIEW" PRIMARY KEY("REVIEW_NO")
);

COMMENT ON COLUMN "REVIEW"."REVIEW_NO" IS '후기 번호';

COMMENT ON COLUMN "REVIEW"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "REVIEW"."MEM_NO" IS '후기 작성자';

COMMENT ON COLUMN "REVIEW"."STAR" IS '별점';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '후기 내용';

COMMENT ON COLUMN "REVIEW"."ENROLL_DATE" IS '후기 작성일';

COMMENT ON COLUMN "REVIEW"."MODIFY_DATE" IS '후기 수정일';

COMMENT ON COLUMN "REVIEW"."STATUS" IS '후기 상태(유지/삭제)';

CREATE SEQUENCE SEQ_REV_NO NOCACHE;	--REVIEW

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE		NULL,
	"REPLY_NO2"	NUMBER		NULL,
	"REPLY_TYPE"	VARCHAR(100)		NOT NULL,
	"REPLY_LEVEL"	NUMBER		NOT NULL,
	"TOTAL_NO"	NUMBER		NOT NULL,
	"REP_COUNT"	NUMBER	DEFAULT 0	NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	CONSTRAINT "PK_REPLY" PRIMARY KEY("REPLY_NO")
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "REPLY"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."ENROLL_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "REPLY"."MODIFY_DATE" IS '댓글 수정일';

COMMENT ON COLUMN "REPLY"."REPLY_NO2" IS '대댓글 번호';

COMMENT ON COLUMN "REPLY"."REPLY_TYPE" IS '클래스/후기';

COMMENT ON COLUMN "REPLY"."REPLY_LEVEL" IS '1/2';

COMMENT ON COLUMN "REPLY"."TOTAL_NO" IS '클래스번호 또는 후기번호';

COMMENT ON COLUMN "REPLY"."REP_COUNT" IS '누적 신고수';

COMMENT ON COLUMN "REPLY"."STATUS" IS '댓글 상태';

COMMENT ON COLUMN "REPLY"."LESSON_NO" IS '클래스 번호';

CREATE SEQUENCE SEQ_REP_NO NOCACHE;	--REPLY

CREATE TABLE "MEM_VIDEO" (
	"VIDEO_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEM_VIDEO"."VIDEO_NO" IS '비디오 번호';

COMMENT ON COLUMN "MEM_VIDEO"."MEM_NO" IS '회원 번호';

COMMENT ON COLUMN "MEM_VIDEO"."STATUS" IS '영상 시청 여부(Y/N)';

CREATE TABLE "CURRICULUM" (
	"CURRICULUM_NO"	NUMBER		NOT NULL,
	"CURRICULUM_CONT"	VARCHAR2(4000)		NOT NULL,
	"LESSON_NO"	NUMBER		NOT NULL,
	"REF_CUR_NO"	NUMBER		NULL,
	"CUR_LEVEL"	NUMBER		NOT NULL,
	CONSTRAINT "PK_CURRICULUM" PRIMARY KEY("CURRICULUM_NO")
);

COMMENT ON COLUMN "CURRICULUM"."CURRICULUM_NO" IS '커리큘럼 번호';

COMMENT ON COLUMN "CURRICULUM"."CURRICULUM_CONT" IS '커리큘럼 세부내용';

COMMENT ON COLUMN "CURRICULUM"."LESSON_NO" IS '클래스 번호';

COMMENT ON COLUMN "CURRICULUM"."REF_CUR_NO" IS '세부내용번호';

COMMENT ON COLUMN "CURRICULUM"."CUR_LEVEL" IS '1(주제)/2(세부)';

CREATE SEQUENCE SEQ_CUR_NO NOCACHE;	--CURRICULUM

CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_CATEGORY"	VARCHAR2(20)	DEFAULT '기타'	NOT NULL,
	"FAQ_STATUS"	VARCHAR2(15)	DEFAULT '공개'	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FAQ_TYPE"	VARCHAR2(50)		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(500)		NOT NULL,
	"FAQ_CONTENT"	VARCHAR2(3000)		NOT NULL
);

COMMENT ON COLUMN "FAQ"."FAQ_NO" IS 'FAQ번호';

COMMENT ON COLUMN "FAQ"."FAQ_CATEGORY" IS 'FAQ유형( 회원  / 클래스 / 결제 / 시스템 / 기타)';

COMMENT ON COLUMN "FAQ"."FAQ_STATUS" IS '공개여부(공개 / 비공개 )';

COMMENT ON COLUMN "FAQ"."ENROLL_DATE" IS 'FAQ작성 날짜';

COMMENT ON COLUMN "FAQ"."FAQ_TYPE" IS 'FAQ타입(MEMBER/TUTOR)';

COMMENT ON COLUMN "FAQ"."FAQ_TITLE" IS 'FAQ 제목';

COMMENT ON COLUMN "FAQ"."FAQ_CONTENT" IS 'FAQ 내용';

ALTER TABLE "LESSON" 
ADD CONSTRAINT "FK_TUTOR_TO_LESSON_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "TUTOR" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "INQUIRY" 
ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "LIKE" 
ADD CONSTRAINT "FK_LESSON_TO_LIKE_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "LIKE" 
ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "MEM_PAY" 
ADD CONSTRAINT "FK_MEMBER_TO_MEM_PAY_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "MEM_PAY" 
ADD CONSTRAINT "FK_LESSON_TO_MEM_PAY_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "QNA" 
ADD CONSTRAINT "FK_MEMBER_TO_QNA_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "QNA" 
ADD CONSTRAINT "FK_LESSON_TO_QNA_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "VIDEO" 
ADD CONSTRAINT "FK_LESSON_TO_VIDEO_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "CLASS_FAQ" 
ADD CONSTRAINT "FK_LESSON_TO_CLASS_FAQ_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "TUTOR" 
ADD CONSTRAINT "FK_MEMBER_TO_TUTOR_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "SALARY" 
ADD CONSTRAINT "FK_LESSON_TO_SALARY_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "REPORT" 
ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "REPORT" 
ADD CONSTRAINT "FK_REPLY_TO_REPORT_1" 
FOREIGN KEY ("REPLY_NO")
REFERENCES "REPLY" ("REPLY_NO")
ON DELETE CASCADE;

ALTER TABLE "REVIEW" 
ADD CONSTRAINT "FK_LESSON_TO_REVIEW_1"
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "REVIEW" 
ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "REPLY"
ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "REPLY" 
ADD CONSTRAINT "FK_REPLY_TO_REPLY_1" 
FOREIGN KEY ("REPLY_NO2")
REFERENCES "REPLY" ("REPLY_NO")
ON DELETE CASCADE;

ALTER TABLE "REPLY" 
ADD CONSTRAINT "FK_LESSON_TO_REPLY_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "MEM_VIDEO" 
ADD CONSTRAINT "FK_VIDEO_TO_MEM_VIDEO_1" 
FOREIGN KEY ("VIDEO_NO")
REFERENCES "VIDEO" ("VIDEO_NO")
ON DELETE CASCADE;

ALTER TABLE "MEM_VIDEO" 
ADD CONSTRAINT "FK_MEMBER_TO_MEM_VIDEO_1" 
FOREIGN KEY ("MEM_NO")
REFERENCES "MEMBER" ("MEM_NO")
ON DELETE CASCADE;

ALTER TABLE "CURRICULUM" 
ADD CONSTRAINT "FK_LESSON_TO_CURRICULUM_1" 
FOREIGN KEY ("LESSON_NO")
REFERENCES "LESSON" ("LESSON_NO")
ON DELETE CASCADE;

ALTER TABLE "CURRICULUM" 
ADD CONSTRAINT "FK_CURRICULUM_TO_CURRICULUM_1" 
FOREIGN KEY ("REF_CUR_NO")
REFERENCES "CURRICULUM" ("CURRICULUM_NO")
ON DELETE CASCADE;


insert  
  into member
  (
     mem_no
   , mem_id
   , mem_pwd
   , mem_name
   , nickname
   , birthday
   , gender
   , address
   , phone
  )
  values
  (
     seq_mno.nextval
   , 'admin'
   , '1234'
   , '관리자'
   , 'admin'
   , '1990-02-02'
   , 'M'
   , '서울시 강남'
   , '010-4309-0984'
  );